apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zephyrusmc-panel
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/external-service/zephyrusmc-panel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

