apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: panel-zephyrus-mc
  namespace: external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
values:
    service:
      main:
        enabled: true
        externalIP: 10.16.60.10
        ports:
          main:
            enabled: true
            port: 80
            protocol: http
        type: ExternalIP
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            entrypoints:
              - websecure          
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: prod-zmc
        hosts:
          - host: panel.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
