apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:/dref7YT8Qq9a1DPKXiK6/FcG8rmyEsCucwk9dBEhl33fDffmv5lauFNNt4Xka2QdTiCh3BWCBN6siPkPm+kAJk=,iv:wK3TwysFZnfNtN2HT5/UMcpUIUiyjI1wU0IFAbvyvAc=,tag:UPCa7VeRqgzGw6GpWNBWww==,type:comment]
    #ENC[AES256_GCM,data:vIiBCvJbTalHu52C5aeUoTlDB8KPJi3TY2E/vrwN3fJHvS67KmreLTYAyIU=,iv:cpwa2E4wVoKFPdnZw0vaErkdzz1+CDmqGUut6hkl43w=,tag:nQqUKRNHcCoj91jCc2niiQ==,type:comment]
    VIP: ENC[AES256_GCM,data:jbBB1us5+I2LdWR/,iv:jX84imgcxGT6483kFSKaY3/PJYbz4zlVEuCA/fRjMGg=,tag:F5v4SX7GKsDD0SpXlBuNXg==,type:str]
    #ENC[AES256_GCM,data:wEQDXtusgBZpJZXKDjZ+DHfZ9508r/YW2Ok=,iv:iX4LvT7A7Xz7ZcUJCugPz4FcaNbB86EOIwdmb5EFfmo=,tag:EDSvasmzSV8q9HTTG3TSOg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:SpySJZB/M+kM1cQ=,iv:C9m1UD6fLjok2TDZKZynbHIZgDhLJWvTVllUG+mjsmc=,tag:kKsDA1XnK/ej3KlbJzVtrQ==,type:str]
    #ENC[AES256_GCM,data:TzDF1rndKLjEsncj7/XeIAJGu5EQS9nQzPP2vCc9NR9VOw==,iv:zBQpmyBg+KaCsgl4CllyMNYMPddZ4ELb0FtkI9vZSO0=,tag:bEYlUHcfES57TyI/sQPGvA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:rAebQpkQA9HJTw==,iv:Kq+EMqRXHbn0OuJkBiWZr2PiAiEdYbIwh9+Gj0nQqbc=,tag:6wzTdp6LKaJBvc2KJAVoTQ==,type:str]
    #ENC[AES256_GCM,data:Pn9Nei8MVDkD9VUDaDzwg+fRP1DcMAUHKeqjVrt2v423TsOuZZ+DukEpnJnwBjs=,iv:/CXMCZputXKrUEyG6I37NOFpZ4fiB4IcPOsQK9sd7zI=,tag:CmP3Sd4CFNoDu0Sp5OtuAw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:VZwLQzpH31DMLwYiu6SmsnA7Sc79NibbJw==,iv:qSqKhiUrqzkW0OOic5IBXxZVaouC9JEIzl64wMneML4=,tag:JKnh/M051s/FxwP9Wr5DEw==,type:str]
    #ENC[AES256_GCM,data:W6E+m580yZ+YkTYIWvFMbtTDbyDm3xlmpRa7OHJk2aw7YRpM25xKYtIDUKtK1Ra+G6Mcfsty9R6B1l8VxYll93L2lUboPfdZag3hE3wxSmmp3lz6uNaKNSwnsg==,iv:RTjY3sX+ABQZ9UFpkes7ZlyZbjxUFubErAaSnEc66VQ=,tag:w4W9eWNC3AiS0fpYlSRjdQ==,type:comment]
    #ENC[AES256_GCM,data:TcZ/WbD2XxGJj9nDQiYZ/btIlaJg2qZ2+MAYAkmzECfP3eHhCq6tICcTpGfrLkjE7zjm24wbnpj/ceiaYLJnPjZd,iv:TqUMWQilZ07/FqWgXugo+k+jZwu/9Dspwcg4A6empjY=,tag:LaNHLBNovd0h20jkXsYBug==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:zGhWtz8v2p8iYLq4,iv:6JWYPfyfuNP2Izbc0R0SnhCJzhKspJC2tDzI10tXfdQ=,tag:0S+lJK+KoAM8RpK51VsS0g==,type:str]
    #ENC[AES256_GCM,data:8MJw1SHROtpHI8NpLdDGVO2Dnmj9Gv+pSpbCiCu8D/LLcyCQXe4iro/P1cFu40aKhuOdYFFQcdFgQynOsIvbDLBMuxkCKO8KKDm2+/WrEJEv+BenvkQ=,iv:dtF0T+Czgcq8Ldo3hK62elw8HSbzar8Tmnl1TWndAMs=,tag:rUQFALl/9y8tfc/pxOo7sg==,type:comment]
    #ENC[AES256_GCM,data:Dy4xFdJB7LlNjEDPZeHTmFWCuNvgZcE/NJ8pL9MMZKgD01hgJDseUf1bN17s+CDAhsPEVN3a6duEQc6UxYzGmYIK3MFtuhHJ32UK2svTJ4/zpq1j+4H4Z728aldjx+b3MoGzcSBhBwiee+hg2HI1lGoh,iv:/XXDypx9cbw/SVU6ZHaRW0BcJpEBBlOrPD2eFt7Wnp4=,tag:RnbmYHTYVMDzIGhpiadYQA==,type:comment]
    SPEGEL_IP: ENC[AES256_GCM,data:nXx5fPA7UDFa0gb0,iv:lIIODWQZRqCBY1/+wrgvzuvIDxVtYdp3KlvBuOd2CGg=,tag:gNYAVAkjSN5tpf+K05kw/g==,type:str]
    #ENC[AES256_GCM,data:dCnRmFocPbxa34HGbhfu0rH0E5b1N4/tZays+BjMDc91Mbw8Rbmgb5PpA0gWX+7UHUESE4XLG+I=,iv:i5MmPCmo5Csy23GbUVpUcohNBaFjkaLew9IGbRgBKlo=,tag:hV24gBZqfoNBrYmSIWMdcg==,type:comment]
    #ENC[AES256_GCM,data:CGcDwBl6wu+rUCfVimDjXbszuUH3BhYOlw==,iv:C/kPC5JVB8BIX319OgXMEMy0sGaSxNDcvPaKwcIek0g=,tag:X+INWVnzC0BG724g+zJIXA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:U+0mP7m1gcejGH8dtg+RkDUEXPUt4mEbmnJRi4FgWH8yja+oIXpNM5OX7r+ck7Fz,iv:D0A9/bH+8jqRJV50K9fioKyUaZvM7710+smlKk8QmNk=,tag:b0Jn9+XRzlkQQPCIVqsblA==,type:str]
    #ENC[AES256_GCM,data:4jQZXipgW8uCmech5YDd8ixNVQVfoqGONPtXT0zi9uorYU+Pm6cp+6TyU/DgVQYYIq2oTl4xJvMuXBvB6qyHjryN9yFch7o=,iv:5X1QpBGtssbzTFQPMlldCSWWShBs/UVGc0En6yXBupc=,tag:DvrGN0eZom6Q97x/Ng+4gw==,type:comment]
    #ENC[AES256_GCM,data:GumfVYIhLQCXlUzvdM60/4dVR3WlEYk/8FaUJZ48UH22gnX2nVX2gjxav3HwMCLMQTCw25HI,iv:mGULaMJc9g1nrdxqLrVRXZjyUPRAG982uvyAqXmDXnw=,tag:JWGw2vJNbY56odoQreGUyw==,type:comment]
    #ENC[AES256_GCM,data:mqMr1mq49babpGI9OUCYojkr/P/PrqScDTFO/D0HYpd36Z0=,iv:fG24Onc9vitkoMkwCLVgQXIgB8FgH46rBZNcgxg7BIw=,tag:QZ6ZfoGcdfPHpoZg0l+lfA==,type:comment]
    #ENC[AES256_GCM,data:1vMOTwmX10V6RBJ5KwXIZMR+eiXFTSuBl6/oG9g60X4O3i/d9vfl,iv:FDhmT5UiuSzJ4abm2xkzYsPzCuy3HSCNjv/Dmptd38M=,tag:8WpViXfGZuwItLMX4j1YBQ==,type:comment]
    #ENC[AES256_GCM,data:LcnzXMuIZl6jcCL9nA==,iv:Bhh7L7StYy7L4J8v3G31OEos2UC1IHBtfDGcj13xUzg=,tag:cpAb+9igkb4erAM2YV/4vw==,type:comment]
    EMAIL: ENC[AES256_GCM,data:avZg1cw5ehEgSXtHk9uUOdkIUQ==,iv:aq0XgotqxusEWP313u1Pd6ws4NcImjD01XWj9Zo3xOQ=,tag:YMiqQkHtVAWh/nBHdhS2vA==,type:str]
    CLOUDFLARE_TOKEN1: ENC[AES256_GCM,data:Ux5LwrE2huTMZKTjJElV7NlSxy8CQacEu3DVlCoqffoC/EuRo78aqg==,iv:5QZPHud+17/0DyGDFk9sYnqq3Cq63le0ehDS6CDm5UU=,tag:3xKC2DxDoEIIdt4+aL/Uew==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:ORbvWeUtR7zSMDw0u0A7,iv:Om+7suYfV95sGlmoCcSsFbAAtVN8/vwXE0LRYa/Jzqg=,tag:/Z42wRCq3DBO2g8YzUyBOA==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:btu4MTn0A2+e7ZUlFbCS,iv:BEyIFBqNhde/S8dShs0a5CCzjMMzwHgxJHSsM/lZOnM=,tag:VWMvPiHAkSD8tU28laks8g==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Dcu01qrbC5Z/YpqL,iv:yh9VLXzZsGTEYFb/6ljyCpKR4pfuPiKuKmO0f3kK1XE=,tag:YCvjCnFNHkBlCLVR/uOSDw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Pda1EnIUd3owNIME,iv:kfNVZijDc+9BHVXSAhBCcQ7sPR1x0o/dgJVE9XZteew=,tag:73yxP6GcH6iOh+wDoeDVBg==,type:str]
    #ENC[AES256_GCM,data:eF3SddgNUimqNi85d6g=,iv:nHXkYbm8TuKu+k0oebRzghdXAoMGRqS04l5jvoie6ZY=,tag:+PgFvvtEu6T45L+ubDlasA==,type:comment]
    PODNET: ENC[AES256_GCM,data:4PrY0K6ap1Xc3U+rng==,iv:rGkbp21Z6Pq8Glge5ejx87gsbrQNDn24JbUwfWTHOls=,tag:F+dPoBWIhjmYyjwT9ZYyWg==,type:str]
    SVCNET: ENC[AES256_GCM,data:me4Li65tEy6IAgs7Cg==,iv:Q4sZFtDoYDFjChYW7dDxWbcc17ChNo0859m9PeL/S7I=,tag:hDth75Df5yDeb7gH8BUnfQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:UDX8ZA==,iv:viWP26gS5uVgmFEQ5rWMXQ8rF7Hke2DLfElndEHce80=,tag:XohWPZgC6MIMOidr7wLMHA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNnA1MUNqN3ZnTjRDNTky
            YkFHR2VlaFd2RUtCaGpBVS9LV3N1S1M2MEVvClM1VXdPRG5EWXZSejNxQVpyV2Rp
            dU9pblY0MmhzdDd3UURoRE5SSWl2VDAKLS0tIE5QQ2MyTVRzS0Z5aW1GTlEzWFdw
            c29CTlBYcHBuWTA3NTd3bXJRU1grL0EKbMz19DbfGUWXS6+V8Q83uQzTLUtrmvW6
            ceaQLlIRJisdbZEBYdQUpcm4XvQ7z92/NUQKaipV/ubos2hUJsaYug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T12:23:05Z"
    mac: ENC[AES256_GCM,data:OZ89vzegWNcNUQFZZj8ggHiRs7foLfpnM4bo5mGOSieOnS/8kTIsWRPBtcu1jbUouPjRFkGkdLwptKqLNBfFhcsqdZG5dYcJH3XdIJEYMT6xS9T9tVjYF/7ZPSM6PeBaPuOeIroFQsN4KNlq/c7qPCT0ClF/FVSg3m4q4tFOpus=,iv:xMeLae/wkb7wcsZ9chaqE1Hiz7QNv9BhiLywqwLmcUg=,tag:lcZTUGWeswhuPlBgTgIXJg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
