apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:umDOY/DaEbJ5yoBsIdug7yXP3H9pY5S69tjCoJRdnlIXUPw1kQnKP6ANoac2+7j94Vu+/JLyOShkelOkHCo/YYY=,iv:5+qaw0GdkU6Hb/EBKO6actCOV581e2VacwepppkVRHc=,tag:xMzc0vMqn9LAFLTGpy16Ow==,type:comment]
    #ENC[AES256_GCM,data:CFqKzLmO/8XuERNQQmYYWKtk4NOe4fckBgBTYIQVf65utUi+0g14WhESxqA=,iv:heVf9bRhIFGKJI9kn71wYPxx1UFHh/UyvR3SW3pWfJA=,tag:WYfYLjdsIwtmsyBHE1rKZQ==,type:comment]
    VIP: ENC[AES256_GCM,data:Qt8+0Gn/1s4eyHcp,iv:g1hnlgmQ/RceL33k+io5Yr9/0/A3Kwhc0/om51DNOxA=,tag:NKgdm+KklHHZjL/eVRthAg==,type:str]
    #ENC[AES256_GCM,data:Oy5euX42cco4jQl2p48w95+3VAwEkoy7cuk=,iv:ouvEw2KvcD3IutGF2eZxiIYjKFRbFgqgLpjADrhL3XU=,tag:dgi8S5UveUrHZ71jwUAtSg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:rRAR8MPJUqZ73+0=,iv:zggWcclGlpcvIH9kzPGtr3ET9mka+lDJrUzx8Y8Y4Oo=,tag:JQjoZz78ziSpvCU6ktUo1w==,type:str]
    #ENC[AES256_GCM,data:/P0TlHlgoS7zZTtfSWt+fDPkhiSxC+F0WLfOE2LJh5MbJQ==,iv:IonuJjgjbdkL0XcA/D/nFn6KPaIwRkylOKRXz8llFEY=,tag:gGS0KCwX2nnBEE7lYgR2KA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:us87GbGsJjj4Qw==,iv:qHmudFzlbaYvQWwXbo3cj85KFH2cEk+obtMLg3z/MlI=,tag:xpTB92Nkm6RU+wEC+8AofQ==,type:str]
    #ENC[AES256_GCM,data:dDRIoXvILe88SekY6r1tdUm+1HakynLDOQqUZouBTAHLQKpET1H8xYT0Qshbw0A=,iv:QcxhR5NKSQcrLxXyv/KunFnsHkfrtMDIoscUqrnnq8g=,tag:dTWEz+twsSFAJHtWM9b5Lw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:eei2hLI2WB15N2O64mjYmXHXtLzNtJZ7GA==,iv:dqef1ovBF7SIOJf5EV90fet3Ymaeq2aNBok1yDdjW0A=,tag:ZdSnwW6cbygaMvXx/FWXAg==,type:str]
    #ENC[AES256_GCM,data:RzsoqIdC1yQit20esif/5sTSHXEJSHy2bhTzyFqweJFIXRT3HnfEwF7JBQqyjtPKP8GzuZ7+Hr8ruQR+BexfRqhqVqzhTI12PzlrB2TODJl5/DgMUZQmllIVoQ==,iv:TzJ6pqa7wpORNiCDk4SX+/Zp5c8DUqdeiYLCs8PwEcE=,tag:2wQYjhmgEABgLy7XlKB2zQ==,type:comment]
    #ENC[AES256_GCM,data:A+ck0Z0Jr1YrE0Fr6tqKfePldrIv0hwJczkM3xgQoitHE1yIjc7jc0F4Wux51HgJ8xpFflcv/+b2neB7Djqfqjdl,iv:oAKwJ+68tUQRA1n075lSsWBGojAvNyTc10rOKo84Af0=,tag:olMrNO9RKG7BE3ycKql75w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:BjBsTQ7dNA/7dCVi,iv:5oSvuCVKt+yv+dVWCMYbNj98WbEmbXpZhHWXKbi/F1Y=,tag:mRLgFa3f/SQmvYlgdYUTjA==,type:str]
    #ENC[AES256_GCM,data:2cYrh2JdMLQrlBlf/aaPH6A60aoBlrWIoN220C3HBnK22PzNGKVFOh/RUfNdP8Hj8FzyE984LMJrlcflcF2epi2GQzSY6C7HP1IVt0lIVF6psfLQnbg=,iv:ZZy3RsVFXZ33ypv4Axh2FtV8VNAAAFuoaAESis7YMD4=,tag:JKYPWctj8RsgpmWkbb73VA==,type:comment]
    #ENC[AES256_GCM,data:Uc4lHnhCrTPccZtVaFR90mFQwl0WmJo/TJ1Y6lZUehnNXrkDKUzzTM8uA0e5nOwUtNLHXxtOTKgCxM6XQ4Ch81UcsvBUCSqO+9JFvNsMfkQPkk9psHXuffD5jcaw8PNTxOjiJ9G0dR4p8dx+VWduvtIc,iv:j7ytcqT3/tC5HXXsTFn0PU6f9+PtKbU+ypezUXiepwU=,tag:rVB2sjLHmFLbD5iYdIGvNA==,type:comment]
    SPEGEL_IP: ENC[AES256_GCM,data:9RDMpPYVw5bsNOV4,iv:hs9f71tY+OKNf+zXaoyBGkSrm6SB9UCIoTzzVOi17lo=,tag:ChwZoYgHmqRjcQuPPrG4pg==,type:str]
    #ENC[AES256_GCM,data:jco1uSYefOPLO9TbYhZPZ23hz56IKtZYe3F2Nh6FLqGn1Jaok+iUdwDaoTnx5g1DHAjEclvB8V8=,iv:hs5YuAFKnmdgHBvQjC3ozvCOIHJXuenG8Eeb0HyNZBY=,tag:m6XtTXFTHbDqG/XA4cPgCg==,type:comment]
    #ENC[AES256_GCM,data:wre7LzX4+XD1kf94IUm82Btdh5nXHheMGg==,iv:SKC8e08XakijwLmT2veIcFnjsBmlpRKnJZ0Fk96Y0Nk=,tag:UnY4wSeRpVj7RLxHx8cwZA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:3gop7RdABKpveoMoTvI2YQFykxI+mUNsSyEkEs1TN4SAHac4rbBXTRGEsOEzaCE9,iv:xeirOQ4il33fHpq6+myFebceAMM55ymjuJS8ko2mHmc=,tag:MsFysRCqoqCzl2M5qgWFOg==,type:str]
    #ENC[AES256_GCM,data:FCIErL0PmxX/42tR3qwGFIIr+dkyOFYzi2pMW6ZRExfSWcED7iGNpWXYUEDIPY3QcBBEnvGzTVhRIk0GUoTtFuLA1A+fu8U=,iv:oiuzbmB/skeEjp35xYZYQfxI2Dz0Z+cb8weZoyEpc78=,tag:yvUrAcPpbPFlzaVq+pMz4A==,type:comment]
    #ENC[AES256_GCM,data:hM1lBUnozzdn2Up0RdIfc2ZO07WQdVAXW+97pGdSqkP9QLP8eHIOAEB/FNtkKDTrbYux27Kg,iv:hN6zouJediBCnFF3QKQVBAENv+RREt58debBbnVtT2Q=,tag:b+9YhvFOCoWpw/xDBkfXbw==,type:comment]
    #ENC[AES256_GCM,data:YEKFNjqzUOswjf1wEtHhqCZ3WT/itIdMj3p1b0B7KBtJXU4=,iv:xTbWJHLNXDuwt89dkMgRA4lbEDofLI3njwc36gbABfk=,tag:w0fzBp95zRchoMS6Yme4pA==,type:comment]
    #ENC[AES256_GCM,data:PUeRc9zJB1C1m8nsiXzdSrFRa0HEG6yFuR/N4/Pa1lLle36zbtQW,iv:EiMsjOdYGZhXANOnawqSp4sLYqVxsvYZrnMcjCrctgo=,tag:pN4BeDKK+0JB+ZUIC97GEQ==,type:comment]
    #ENC[AES256_GCM,data:uDL4mmtZ5/ifghlBA8U=,iv:0hoxmTXLhXm/E38pMyXD9MRUWoVWLl3NL3xxkXCnAys=,tag:2QpKHHnmlEDBv6nGxdjPrg==,type:comment]
    PODNET: ENC[AES256_GCM,data:f1SLshFNggmUGKqKbw==,iv:s/SfHsRb5J/t2csTc//IfiaewODhK3CRXuKGKfgTbCE=,tag:XLNd9fpyrYbDgvOwZcxJAw==,type:str]
    SVCNET: ENC[AES256_GCM,data:vWSO8YBLGxquFArmBA==,iv:oSGXpjIcMFF2fHitl5gNSzRTKf0x/VbzAQaO+ViGF9w=,tag:vdUPEq7s9m2JZnPLZTXQOQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:bN8AIA==,iv:T5wAC+3X2NQu6ceSVdNm9AuAi94pcwhRyJE0qlGEl00=,tag:Ps5U5UKNOQ49XElXUfR0xA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRzJCenBHcUNaYmdSclNl
            MktlblU3V3E4SDZKREgzZlcyeWxreEZKRUZrCmNORjlIMi80Wkh5U0ZXRlVSMDFp
            b2RCclpqL0ozNGhlQnZTVmhCVk5leVkKLS0tIFM0MlA1ZTZCNGx3WjNZTE1oZmRC
            d2d5emY3ZGhxVG8xVE15bVBIR3ZNVk0K5LP8OXwksc/ePcLsZFfxW8UF5PelgVnP
            3M+ARs2zhLDj/8vi6QvBW6QIn2SgOSx3CKnVBV63VGxBucwnXVqZlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T11:28:13Z"
    mac: ENC[AES256_GCM,data:HWrb+pmdE/6Z6rpjdFLW8Xete/qGQvLNJ+/7WJ02h3QuuDs2khw/yKRlM7t/C6wHGYPIXIV2/BD9nHPcG4T1pXqLCQ5K7WD1J9Pygj/WQuWstUbrZwgtnMIBqUtBenN+uM9wDf70VCZJQK4gUoJy6ppIEFEr48HZyZZnLKals+Y=,iv:T3SVAULKDsHcF13oJINmT9uxxx5+FBe1UhFZP0Kz6Bk=,tag:MoMGGaqd8UxLgJ7OGfsKJg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
