apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qiHwkKjXJAWowP/Mna23YhITXxFxakLR7auKcFAqEHtiTiS48wewto/BSzry225rIanJv6SIKklcRrEPIq4h/KMVlk2nB7/HXezhsGPX5wTQR/eI40sK+jgbshBnq/X7XQRouN3ZJrdblK2eRIzoy39ERDfzbsRDIml68DlIIEdGnLIXq6MriYqZc6tFyqbXVcm4Cn+qrKnhA8Ny21YIA8AJ6/E5kcUEYDLArH6LWOtQArnzGMn6FWsp5l4ktfl/JEw0eigIzp1wl7jGQazK82ibubKTa3UXB1SASXL3NQ9DO1HdURz2MPpplfyTQPUpEUXvxEw+a+k+ZrdDEk8sWX63FG+Yhv8rilBOdANU/4/w+q/+yepJknXTc8hHYM1M,iv:eluzEftohUUrnVlIoARnFxu4UHe/AEfjbFeu7BMt+zs=,tag:H/UMWkBh6w2v4tWUz3tcXQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5X5EnDLMBrXOIpSRhKzjfZizZidKZzkzpEgCrQXgSVt2yIY81TsiIu3KNk7X0rETxfLpuf7Hjk+ji5oShQnm8+QWcET5Jv5fN0LbqNhsAzMvaW+shrcAEI1YrYZItwFzbZWeG7SNUtbrrRlLorHXmWLS+ITdx6lX5mngT8ikb2/X+sBUYbHUnkJtAoUltkwAXyYyHgd5po+wJCi9M+IGNQkMEZPREqDQJtgrK14SUbNpJrC8ZCxN/Z4/z1MtPPSVaiNfxVpANOjbJkrEgg==,iv:L363gI3jQTyJsCiHRKeYEcYf9fQqayOfCfYJNbtg4Dw=,tag:syvLkAYz0AFTLv1l96I0gA==,type:str]
    known_hosts: ENC[AES256_GCM,data:KIFAgc8SzRqwNTDuMFrh3DMIqC8hxHRnm3LFqct3WvVmITdPKxGwAexPeBozl+GcReBz/pkTo2NWLDleeLyZjlt5RBiV6lhix0RNHTzjN0StraRmTRNEICBTZzRAFvlaNCn8ZGBwP9EH3zT6pdEbkJRXqxd5I2x/hd/3GNbO1apU9WGUfqXHST9B/DO23Jk3zTmQp5et+sFY2Izv/NBXqiUzKdqBs4uLRPca,iv:q8ft0+pkpRZfzNH6gox1Tsr4sTw06DuLraUguRgt0DM=,tag:cAfMZw449Cf3S5YBQNnWcA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ0VXQWxYMTNVNnIyNW5u
            UGFXQ0RDMEJoWXdHUmJKN21RaTB2MGU3d2pZCnI4V2NPRkpoVjluSGViZUdEVjVQ
            SUdkd0t3RThkVXhick1lVDFCMC9TZ1kKLS0tIGxXNGMwdm1xR0xNaVg3Uis5Q3My
            NTIzdFFZQTE0SU1ob1hyMElpcFBwTHMK53EzrmvBcnxuXJO5TxmeZJ4bOHM18JAW
            sRnUTg9YUESjubtFzu3LPKYAMb/pRuhkw0agCMCfg7ImKYxTrqv0bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-29T13:44:00Z"
    mac: ENC[AES256_GCM,data:zVqP4SndFEdufpopDOJjyn1iLhoiHIOMD8w35bxVgg5ATk7Rvv4iDbxQlpTAEx1qBLpt6zgJ4h8MeJz8Pv5bsK1cMsGf2o/njrDxQsscoTAJ7HEa3D+5wvVZBUuqM9KbVjfm1g0CwxNjGvo3KyJfeJUqOSQEgQEQmUcRmkJRHCs=,iv:Mnec9UpeGXc6OMw+ghxkLvIhotfO/UKIiOHeK7BMyaE=,tag:F85HvIEe2AiqFPIOEbSDjA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
