apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MkOWhxiazSUYGncWfvl3azHLs4Hj3L2tJbzzqciBCFTSwAhp57JwyVPf7q78ziMN9OGqRn0RXF3T06MYMyhpehHSC5TNvYOhv8HRBeSu/3NZ5ApLAeVve/Zd8auiQqMA3lBAfjNczFoQ/H9Yiyqiztoq0sTry309MnhEZmESaleo2zhwOaEbb/v3DQz7wTrKKftMQ7kitIcN2iM9muTI6PZBBERHyY2b428amjtRfxGHJG7jP4W5ipcac+SkzmPP+h3UQ7X5yQ8Wu+ANrfambg+ojVbxryNlDOB4tnNIoUzezNygwlKThQZm9PgAwbTgiz5Tza2O68nygtjgREmXU07XQ2RiHWvPRCfmctJkR4lmRc2owcBtlFg88fDRJik0,iv:Csj+afJdDxf9qx10upuRsyZweitESB0IFu+jT1pmbsk=,tag:1ZIDPuLxlwQK6NC1rs06mg==,type:str]
    identity.pub: ENC[AES256_GCM,data:E/LMNkZscAyFAnYGL/ZY298NHXH/PIYqNvLPZLcLuU28dIsXJfjsjTsv8o9DMYHKyWbrtBX+JhCLHhVH0xWWSjzzXj/0mnFCpOuLC5g2+dwuF3ThHf6+svtwHzp9wSDyUBGX7f/LUMRRkCLtLjV6R9XFO/AATlPPgc/in2LaFhSU/6sdZgOMggAxBMBPku9lzS/X40Ct45rFLOdrka+vhjnDR7gkNrU7dpuP2sP/JMir366HF6XBoxT3cWthWTXtDm8P7YaABlIcyX2y7Q==,iv:LKsULNDACFTEOWYtZLVTwKUp/g2RTiozPeSc1kkwAT0=,tag:Y0qOzjIU75unpQ2N8LYmhw==,type:str]
    known_hosts: ENC[AES256_GCM,data:386vS87q+j172zUPiDqgLFEqnJgd38fv4eyAI3HouYpsBthdnz370aqtqSsShbiqsL7py7cato63Baj1tMH1tV7J+Tq3f3HaJmGVRVCzY+ePmx8dVi8VgToVUaOZgHGg18H5acQ4a0H1h4awPeAUc7mG92Nlmyp8H15Kvi7ayf2VPblBHD/sEQTKq/EOKztMMvtRA0F1x+4TgZ4Q8Y4z4FXjZYSeLhZeSfIc,iv:KFzE+ygvLcGOd5cevq5TdduIQ9P7j+V8bRXpRcwb/f0=,tag:colamYiItfzSP7KKpH8DyQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWHRjdDAveU1Kc2VORyt6
            NjlkbWFOL3cyQ2g1TitTaU5rbUU4bXZ1SVJNCk0yLzNQL2xoYUU3VmhSdTE4dHcy
            QWRub0lYYkdaSjhSTUZqSDJrd2NoUjgKLS0tIFBnSlhPemNiZGZDd2wrdWFIekJF
            VFZ3UXlLRTBici95c1ZjTkU2VmU0SGcKGI73tv07z4AXlhKVCBYyyg4u8X3twz7l
            E2bPnNkFr3AfsN9Td0lWzpJyo787HBZot+pbRdQZfZP2x6s4/JlUcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-25T18:31:59Z"
    mac: ENC[AES256_GCM,data:wgJ+Xwy8G/4l1rDkYzBiVVyzAXpK2L67nHfCqTF5Yu4VONSRSvvv5uZ8ZVyax7WFuZPXoIPhiknP+Oniv3fFIS1bL2WvyQ+EZ9vbF3uLImDeV3K4BTWJJMuuRUPnofHY0r67G4MQx+fHuWS4Q+6gYXxdZKBqVMA6tJKrlwebDMg=,iv:QAJbSLMLNO4q2XkqMClkZQYHbsOMkWJVajdm91ROB+Q=,tag:4Xej5/VXdlINCKxuuMaOMg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
