apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9eDOy4+AhqmY8o0pKSx087PK28TPa3rGBmOWbbBisXdozwbluQkTEuVL3d6DAAV0b8DKJ4H9Mdk0w0PVzGNelr8WdGpd0yAQj5tp853KkjJre7UDV9RWVFy4t99J6DuiGQm65X/QgU1nqgMWm3RAo6O+7gCkg1a847roJpbKhq313lFAWEZOatkVU0cpmSCSHQ9XM6EeRQC+YqEmv8vysH/beVZnR+UPa8xPzIhd27Jr19cMjyzDY/pMvxcHcCOWfptgoLlYa/qIgvmt2p+v22QgWfh6EginXM4pNvHCeJmI1qABd43DZloOPBcPTY7fORKFNXtvvPV85ODuzw2x/oDimg+gTRf4+QW7c2A+wJIixUV+3XO51+D8cr6s7grU,iv:BRvwAJzo557yLfIOwUYq0yFi9Vj95E2MD1boIYSMSBc=,tag:nfm0GQyq7adSEGMrQls22g==,type:str]
    identity.pub: ENC[AES256_GCM,data:pB2kHPQ4p22RUigXGH5Hdbh6q+uep6unySWI+7WzdKLRt4niHvbpuecbGqXBm4zL1pjSkWOmy7g9xVZ6f/N1bLabJVov36tB537WCMxzHMM0LOHWMHQ6QekRSAmIm1CLNKpyGOzOu44fArI4SGRvQS/V+wRcFpfW/HJQqXECh/DEWpIaP179RQ7slh/QNY+yQe5YEHPCSkXU9yKdmDxwpoQMuZGZrPvF6wnhH0p+Yk3b3M/IlB9BpEm26A70PE1vRoI9D7IkgS0KelEHDw==,iv:W97SoddxxTzx8U/LjSDaGQKiYRWUEUGAMiUnLn86tC8=,tag:EG8QCk19p+ZWOolUgS9gvg==,type:str]
    known_hosts: ENC[AES256_GCM,data:v3ajvFPk0fiNP/wmzx2u3i2Qlt7H3DxBwTqTqQHYrnhFmUoiCDk/XAsBolMKSq6f/i7dVqpLXYdlCUqknheekqzIl3jThgVN7aXUFy8Q2h2RH2fiBXTZh5f3dEEpD4gwUSjv77jj6CiTHhQQqH9ETe1xkOEkbHVrnZ/MFERtCp4S2NYfvV+q40GgpLY1LRiDxbaXTadN0XgI4XrCs44H6RyTMbSsPx9+loQf,iv:viVIv+qdGKNcI1Z02OzYSwVtAT8e0g3KhY2VmIcKCwI=,tag:QKMIYskbpiFi562jIhBfsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVTFsaFhObHFlSmVmS3F2
            R2dXTlFrTGN5UUdGdmNGaENSVnlvTG5XNUJvCnJRaTNWbGNISlNiUWdNWTgzeXRV
            Vjh6S21oc1dKNlhjQ1ZWZkt2Tno0VXMKLS0tIGJ4eUFUdnhMU2ZmZDlxWDBEbWJK
            eEZYcXJxZ282ZXJaOHlEaW83eXFURUEK2In3OSajyM2g5IK1dEbYz6fRY0Tg2Z8l
            6TMCZYGxMW7GJqF+KH1sMOQ4OocHJopBU1ulk3KYkqPgYLAucyNbjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T09:22:27Z"
    mac: ENC[AES256_GCM,data:hha5Y0SRgXixDc19BFNueEIQy/FW0nbROFcyZffCGl9qUH8bN03NWo2zDbczld9NNSrBY2TE5LVovOM5qSdkBUYGc75TBf4iqs94UKGJiTFMY6nOGlE22hjkwhTZMDSQYy8CWGsVa9PA58hQhNvXNJt2t1MqGpJSL/PyRKh5Mro=,iv:PYhKiq5xtZGbHyAbjcivqUwIQR2MSezqDDDU6zMBqb4=,tag:j25ISmVlg0U/LDDF4sLpfw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
