---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: odoo
  namespace: odoo
spec:
  interval: 15m
  chart:
    spec:
      chart: odoo
      version: 20.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-odoo"
        accessKey: "${MINIO_ACCESSKEY}"
        secretKey: "${MINIO_SECRETKEY}"
        encrKey: "${MINIO_SECRETKEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            # middlewares:
            #   - name: private-range
            #     namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: prod-dl
        hosts:
          - host: odoo.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      odoo:
        enabled: true
        volsync:
          - name: odoo
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      addons:
        enabled: true
        volsync:
          - name: extra-addons
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      odoo-config:
        enabled: true
        volsync:
          - name: odoo-config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
    # Enabled postgres
    cnpg:
      main:
        # mode: recovery
        backups:
          # revision: ""
          enabled: true
          credentials: minio
        recovery:
          # revision: ""
          method: object_store
          credentials: minio
    portal:
      open:
        enabled: true

    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true

        service:
          # -- Enable a service for the code-server add-on.
          type: "LoadBalancer"
          loadBalancerIP: "10.16.61.150"
          # Specify the default port information
          ports:
            codeserver:
              port: 12321
