---
## yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audacity
  namespace: audacity
spec:
  interval: 15m
  chart:
    spec:
      chart: audacity
      version: 14.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # credentials:
    #   minio:
    #     type: s3
    #     url: "${S3URL}"
    #     bucket: "${S3PREFIX}-audacity"
    #     accessKey: "${MINIO_ACCESSKEY}"
    #     secretKey: "${MINIO_SECRETKEY}"
    #     encrKey: "${MINIO_SECRETKEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            # middlewares:
            #   - name: private-range
            #     namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: prod-dl
        hosts:
          - host: audacity.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    # persistence:
    #   config:
    #     volsync:
    #       - name: config
    #         type: restic
    #         credentials: minio
    #         dest:
    #           enabled: true
    #         src:
    #           enabled: true
    # addons:
    #   codeserver:
    #     # -- Enable running a code-server container in the pod
    #     enabled: true

    #     service:
    #       # -- Enable a service for the code-server add-on.
    #       type: "LoadBalancer"
    #       loadBalancerIP: "10.16.61.135"
    #       # Specify the default port information
    #       ports:
    #         codeserver:
    #           port: 12321            